### ISSUE TITLE
Bad precision and warnings when running under Raspberry PI 3

### ISSUE THREAD

**Issue by jcea** [nineties/py-videocore#5]
This project is really promising. Too bad there is no documentation and very few examples :-).

I was trying some examples and I see this:

```
root@osmcpi:/home/jcea/virtualenv/py-videocore/examples# ../../bin/python sgemm.py 
sgemm.py:655: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  uniforms[th, 4] = A.addresses()[i*16*h, 0]
sgemm.py:656: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  uniforms[th, 5] = B.addresses()[0, j*64*w]
sgemm.py:657: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  uniforms[th, 6] = C.addresses()[i*16*h, j*64*w]
==== sgemm example (96x363 times 363x3072) ====
threads: 12
numpy: 31.9355 sec, 0.0067 Gflops
GPU: 0.0321 sec, 6.7054 Gflops
maximum absolute error: 7.3559e+01

root@osmcpi:/home/jcea/virtualenv/py-videocore/examples# ../../bin/python sgemm_1thread.py 
==== sgemm example (96x363 times 363x3072) ====
threads: 1
numpy: 31.5038 sec, 0.0068 Gflops
GPU: 0.2676 sec, 0.8034 Gflops
maximum absolute error: 7.8866e+01
```

The virtualenv I am using runs Python 3.4.

The Raspberry PI 3 is running KODI at the same time, but not reproducing a video, just in the main menu.

"Hello world" example works fine, with maximum error ~1e-7.

Maybe this is useful:

```
root@osmcpi:/home/jcea/virtualenv/py-videocore/examples# ../../bin/python mailbox.py 
firmware revision: 57bc72be
board model: 0
board revision: a02082
board serial: 000000008a498dfc
```

**Comment by thomashang** [comment]
I had the same problem (with my Pi2). 
```
==== sgemm example (96x363 times 363x3072) ====
threads: 12
numpy: 15.1359 sec, 0.0142 Gflops
GPU: 0.0312 sec, 6.8996 Gflops
maximum absolute error: 7.7906e+01
```
After comparing values of matrices C and R, apparently parts of the matrix C are untouched by the QPU, and somehow it is related to the matrix division `p_div`, `r_div`.  

I figured out some not-so-elegant workaround, and the last 16 rows of matrix C has to be discarded (which can be fixed with appropriate padding, i assume)
```
(line 617) p_div =  1 // was 2
(line 618) r_div = 12 // was 6
           ... 
(line 689) float(np.max(np.abs(R[:p - 16] - C[:p - 16]))))) // discard the last 16 rows of matrix
```
And yields this result. 
```
==== sgemm example (96x363 times 363x3072) ====
threads: 12
numpy: 15.1466 sec, 0.0142 Gflops
GPU: 0.0303 sec, 7.1022 Gflops
maximum absolute error: 9.1553e-04
```

**Comment by Terminus-IMRC** [comment]
Current sgemm implementations don't output correct results. We are planning to fix them. Please wait a few!

**Comment by tawnkramer** [comment]
any progress on a fix for this?

**Comment by Terminus-IMRC** [comment]
It turned out that inserting many nops (`32*1024` or more) just before program_end of QPU program makes it work correctly. e.g.,
```
...
interrupt()

for i in range(32*1024):
    nop()

exit(interrupt=False)
```

The precision error occurs only on RPi 2 and 3, not on RPi 1. As another L2 cache is added to the system to RPi 2 and 3, that may be a cache negotiation issue, but we don't know why it really is.

**Comment by jcea** [comment]
Ping...

**Comment by Terminus-IMRC** [comment]
Not yet... Sigh... The precision issue occurs only when a QPU program is *executed* and the result is seen by py-videocore. So we are using py-videocore just to assemble the program and [QMKL](https://github.com/Terminus-IMRC/qmkl) (written in C) to run it on QPU.

**Comment by patrickms** [comment]
On a Raspberry Pi 2 at least, the issue seems to be caused by the (default) disabling of the L2 cache.

Adding `disable_l2cache=0` to `/boot/config.txt` (as well as commenting out `dtoverlay=vc4-kms-v3d`) and rebooting the Pi solved the problem for me.

See also
https://raspberrypi.stackexchange.com/questions/36960/why-is-the-l2-cache-disabled-by-default-on-raspbian-jessie#36967

**Comment by Terminus-IMRC** [comment]
I found that [the driver is passing physical address to QPU](https://github.com/nineties/py-videocore/blob/master/videocore/driver.py#L49). Physical address should be used only for `mmap`, and QPU needs bus address. So I changed the driver to use physical address for `mmap` and to pass bus address to QPU, then the precision errors are decreased, though they are still not 0 yet...

Before:
```
$ sudo python3 examples/sgemm.py
==== sgemm example (96x363 times 363x3072) ====
threads: 12
numpy: 15.3687 sec, 0.0140 Gflops
GPU: 0.0314 sec, 6.8459 Gflops
minimum absolute error: 0.0000e+00
maximum absolute error: 7.7906e+01
minimum relative error: 0.0000e+00
maximum relative error: 8.8532e+01
```

After:
```
$ sudo python3 examples/sgemm.py
==== sgemm example (96x363 times 363x3072) ====
threads: 12
numpy: 15.3917 sec, 0.0140 Gflops
GPU: 0.0285 sec, 7.5474 Gflops
minimum absolute error: 0.0000e+00
maximum absolute error: 9.1553e-04
minimum relative error: 0.0000e+00
maximum relative error: 1.0522e+01
```

As a reference, [QMKL's sgemm example](https://github.com/Idein/qmkl/blob/master/test/sgemm.c) works with no errors:
```
$ sudo test/sgemm
P = 96
Q = 363
R = 3072
ALPHA = 1.000000
BETA = 1.000000
==== sgemm example (ALPHA * 96x363 * 363x3072 + BETA * 96x3072) ====
GPU: 0.026288 [s], 8.17829e+09 [flop/s]
CPU (4 threads): 4.72143 [s], 4.55351e+07 [flop/s]
Minimum absolute error: 0
Maximum absolute error: 0
Minimum relative error: 0
Maximum relative error: 0
CPU with NEON (4 threads): 0.541147 [s], 3.97287e+08 [flop/s]
Minimum absolute error: 0
Maximum absolute error: 0
Minimum relative error: 0
Maximum relative error: 0
```

So I think there still be wrong points in py-videocore...

**Comment by Terminus-IMRC** [comment]
I visualized the relative errors of sgemm. **White** part of the images are `error > 1e-3`.

py-videocore `mmap`s physical address instead of bus address:
![out1](https://user-images.githubusercontent.com/4298265/34380727-ff80dfde-eb46-11e7-8b80-3f8e477366b3.png)

py-videocore `mmap`s bus address:
![out2](https://user-images.githubusercontent.com/4298265/34380725-fd978e02-eb46-11e7-9157-baedbe698fe9.png)

QMKL `mmap`s physical address instead of bus address:
![out-qmkl](https://user-images.githubusercontent.com/4298265/34381170-28b13a5e-eb4a-11e7-8abb-d90ebba93597.png)

So, on sgemm which `mmap`s physical address, block errors will occur, which seems to be because of independent L2 cache introduced in RPi2 and RPi3. Changing py-videocore to `mmap` bus address fixes the precision issue! Got it!

**Comment by Terminus-IMRC** [comment]
py-videocore sgemm initializes matrices with Gaussian random numbers while QMKL sgemm filled them with all 1s. This is why errors by QMKL sgemm is all 0s. After changing QMKL sgemm to use Gaussian random numbers, the errors became almost the same magnitude with py-videocore's:

```
$ sudo test/sgemm
P = 96
Q = 363
R = 3072
ALPHA = 1.000000
BETA = 1.000000
==== sgemm example (ALPHA * 96x363 * 363x3072 + BETA * 96x3072) ====
GPU: 0.026019 [s], 8.26284e+09 [flop/s]
CPU (4 threads): 4.56029 [s], 4.71441e+07 [flop/s]
Minimum absolute error: 0
Maximum absolute error: 0.000854492
Minimum relative error: 0
Maximum relative error: 0.548343
CPU with NEON (4 threads): 0.609067 [s], 3.52984e+08 [flop/s]
Minimum absolute error: 0
Maximum absolute error: 3.05176e-05
Minimum relative error: 0
Maximum relative error: 0.0577181
```

**Comment by Terminus-IMRC** [comment]
@jcea Happy to close?

**Comment by jcea** [comment]
Yes, I now get this:

```
==== sgemm example (96x363 times 363x3072) ====
threads: 12
numpy: 38.8727 sec, 0.0055 Gflops
GPU: 0.0282 sec, 7.6141 Gflops
minimum absolute error: 0.0000e+00
maximum absolute error: 9.1553e-04
minimum relative error: 0.0000e+00
maximum relative error: 1.0522e+01
```

I close the issue. Thanks.
